### ISSUE TITLE
can not load java mode

### ISSUE THREAD

**Issue by ghost** [iocanel/emacs.d#1]
I found your wonderfull java setup
I am on voidlinux, I extracted https://download.eclipse.org/jdtls/milestones/1.9.0/ in .emacs.d/.local/lsp

I followed the steps 
mkdir -p ~/.emacs.d/.local/lsp/eclipse.jdt.ls
pushd ~/.emacs.d/.local/lsp/eclipse.jdt.ls
curl -s -L https://www.eclipse.org/downloads/download.php?file=/jdtls/milestones/1.9.0/jdt-language-server-1.9.0-202203031534.tar.gz | tar zxv
mkdir bundles
pushd bundles
curl -O https://github.com/dgileadi/vscode-java-decompiler/raw/master/server/dg.jdt.ls.decompiler.cfr-0.0.3.jar
curl -O https://github.com/dgileadi/vscode-java-decompiler/raw/master/server/dg.jdt.ls.decompiler.common-0.0.3.jar
curl -O https://github.com/dgileadi/vscode-java-decompiler/raw/master/server/dg.jdt.ls.decompiler.fernflower-0.0.3.jar
curl -O https://github.com/dgileadi/vscode-java-decompiler/raw/master/server/dg.jdt.ls.decompiler.procyon-0.0.3.jar
** popod
** popd

The last two commands are the one I did not do.

Thank you for your time

**Comment by iocanel** [comment]
I don't have enough input and given that the user is deleted it doesn't seem likely I'll get enough info. Closign
